const byId = (id) => document.getElementById(id);
const supabase = window.bccSupabase;
const auth = window.bccAuth;

function escapeHtml(str = '') { return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
function getParam(name) { return new URLSearchParams(window.location.search).get(name) || ''; }
function renderPairs(items = []) { return items.map(item => `<article class="summary-pill"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(item.value)}</strong>${item.note ? `<em>${escapeHtml(item.note)}</em>` : ''}</article>`).join(''); }
function renderTimeline(items = []) { return items.map(item => `<article class="timeline-item ${escapeHtml(item.level || '')}"><div class="timeline-time">${escapeHtml(item.happened_at_label || '')}</div><div class="timeline-body"><strong>${escapeHtml(item.title || '')}</strong><p>${escapeHtml(item.text || '')}</p></div></article>`).join(''); }
function renderActions(items = []) { return items.map(item => `<button type="button" data-action-label="${escapeHtml(item.label || item)}">${escapeHtml(item.label || item)}</button>`).join(''); }
function mapStatusKey(status = '') { if (/审批/.test(status)) return 'approval'; if (/执行|进行|作战|潜猎/.test(status)) return 'doing'; if (/完成/.test(status)) return 'done'; if (/停滞|阻塞|卡住/.test(status)) return 'blocked'; return 'queued'; }
async function requireOwnerUI(ids) { const owner = await auth.isOwner(); ids.forEach(id => { const el = byId(id); if (el && !owner) el.style.display = 'none'; }); return owner; }

async function loadTask(taskId) { const [{ data: task }, { data: logs }, { data: actions }] = await Promise.all([supabase.from('tasks').select('*').eq('id', taskId).maybeSingle(), supabase.from('task_logs').select('*').eq('task_id', taskId).order('created_at'), supabase.from('task_actions').select('*').eq('task_id', taskId).order('sort_order')]); return { task, logs: logs || [], actions: actions || [] }; }
function fillTaskForm(task) { if (byId('task-status-input')) byId('task-status-input').value = task.status || ''; if (byId('task-hunter-input')) byId('task-hunter-input').value = task.hunter_label || ''; if (byId('task-progress-input')) byId('task-progress-input').value = task.progress ?? 0; if (byId('task-latest-progress-input')) byId('task-latest-progress-input').value = task.latest_progress || ''; }
function renderTaskPage(task, logs, actions) { byId('detail-title').textContent = task.title; byId('detail-subtitle').textContent = task.meta || ''; byId('detail-chip').textContent = `${task.badge || ''} / ${task.status || ''}`; byId('detail-summary').textContent = task.description || task.summary || ''; byId('detail-stats').innerHTML = renderPairs([{ label: '等级', value: task.badge }, { label: '当前状态', value: task.status }, { label: '当前猎人', value: task.hunter_label || '-' }, { label: '截止时间', value: task.deadline_label || '-' }, { label: '赏格', value: task.reward_label || '-' }, { label: 'Token', value: task.tokens_label || '-' }]); byId('detail-progress').innerHTML = renderPairs([{ label: '最新进展', value: task.latest_progress || task.summary || '-' }, { label: '最近更新', value: task.updated_at_label || '-' }, { label: '当前问题', value: task.current_issue || '无' }, { label: '完成标准', value: task.done_when || '-' }]); byId('detail-log').innerHTML = renderTimeline(logs || []); byId('detail-actions').innerHTML = renderActions(actions || []); fillTaskForm(task); }

async function initTaskPage() {
  const owner = await requireOwnerUI(['task-update-form', 'task-log-form']);
  const slug = getParam('id'); const { data: task } = await supabase.from('tasks').select('*').eq('slug', slug).maybeSingle(); if (!task) return;
  async function refresh() { const loaded = await loadTask(task.id); renderTaskPage(loaded.task, loaded.logs, loaded.actions); bindActionButtons(loaded.task); }
  function bindActionButtons(currentTask) { document.querySelectorAll('[data-action-label]').forEach(btn => { if (!owner) { btn.style.display = 'none'; return; } btn.onclick = async () => { const label = btn.getAttribute('data-action-label') || ''; let nextStatus = currentTask.status; if (/完成/.test(label)) nextStatus = '已完成'; else if (/停滞/.test(label)) nextStatus = '停滞中'; else if (/审批/.test(label)) nextStatus = '待审批'; const { error } = await supabase.from('tasks').update({ status: nextStatus, status_key: mapStatusKey(nextStatus), updated_at_label: '刚刚' }).eq('id', currentTask.id); if (!error) { await supabase.from('task_logs').insert({ task_id: currentTask.id, happened_at_label: '刚刚', title: `操作：${label}`, text: `任务状态已更新为 ${nextStatus}。`, level: 'info' }); await refresh(); } }; }); }
  byId('task-update-form')?.addEventListener('submit', async (e) => { e.preventDefault(); if (!owner) return; const statusEl = byId('task-update-status'); statusEl.textContent = '正在保存...'; const nextStatus = byId('task-status-input').value.trim(); const hunterLabel = byId('task-hunter-input').value.trim(); const progress = Number(byId('task-progress-input').value || 0); const latestProgress = byId('task-latest-progress-input').value.trim(); const { error } = await supabase.from('tasks').update({ status: nextStatus, status_key: mapStatusKey(nextStatus), hunter_label: hunterLabel, progress, latest_progress: latestProgress, updated_at_label: '刚刚' }).eq('id', task.id); if (error) { statusEl.textContent = `保存失败：${error.message}`; return; } await supabase.from('task_logs').insert({ task_id: task.id, happened_at_label: '刚刚', title: '任务已更新', text: latestProgress || `状态改为 ${nextStatus}`, level: 'info' }); statusEl.textContent = '保存成功'; await refresh(); });
  byId('task-log-form')?.addEventListener('submit', async (e) => { e.preventDefault(); if (!owner) return; const statusEl = byId('task-log-status'); statusEl.textContent = '正在写入...'; const form = new FormData(e.currentTarget); const payload = { task_id: task.id, happened_at_label: '刚刚', title: String(form.get('title') || '').trim(), text: String(form.get('text') || '').trim(), level: String(form.get('level') || 'info').trim() || 'info' }; const { error } = await supabase.from('task_logs').insert(payload); if (error) { statusEl.textContent = `写入失败：${error.message}`; return; } e.currentTarget.reset(); statusEl.textContent = '日志已写入'; await refresh(); });
  await refresh();
}

function renderHunterPage(hunter) { byId('detail-title').textContent = hunter.name; byId('detail-subtitle').textContent = hunter.role || ''; byId('detail-chip').textContent = hunter.title || '猎人名鉴'; byId('detail-summary').textContent = `这名猎人当前状态：${hunter.status || '未知'}。适合处理 ${(hunter.tags || []).join(' / ') || '多类任务'}。`; byId('detail-stats').innerHTML = renderPairs([{ label: '模型', value: hunter.model || '-' }, { label: '当前承载', value: hunter.load || '-' }, { label: '成功率', value: `${Number(hunter.success_rate || 0)}%` }, { label: '平均消耗', value: `${Math.round(Number(hunter.avg_tokens || 0) / 1000)}k` }, { label: '评级', value: hunter.grade || '-' }, { label: '状态', value: hunter.status || '-' }]); byId('detail-side').innerHTML = renderPairs((hunter.tags || []).map(tag => ({ label: '专长标签', value: tag }))); if (byId('hunter-status-input')) byId('hunter-status-input').value = hunter.status || ''; if (byId('hunter-model-input')) byId('hunter-model-input').value = hunter.model || ''; if (byId('hunter-load-input')) byId('hunter-load-input').value = hunter.load || ''; if (byId('hunter-success-rate-input')) byId('hunter-success-rate-input').value = Number(hunter.success_rate || 0); if (byId('hunter-avg-tokens-input')) byId('hunter-avg-tokens-input').value = Number(hunter.avg_tokens || 0); if (byId('hunter-tags-input')) byId('hunter-tags-input').value = (hunter.tags || []).join(', '); }
async function initHunterPage() { const owner = await requireOwnerUI(['hunter-update-form']); const slug = getParam('id'); const { data: hunter } = await supabase.from('hunters').select('*').eq('slug', slug).maybeSingle(); if (!hunter) return; async function refresh() { const { data: fresh } = await supabase.from('hunters').select('*').eq('id', hunter.id).maybeSingle(); if (fresh) renderHunterPage(fresh); } byId('hunter-update-form')?.addEventListener('submit', async (e) => { e.preventDefault(); if (!owner) return; const statusEl = byId('hunter-update-status'); statusEl.textContent = '正在保存...'; const tags = byId('hunter-tags-input').value.split(',').map(s => s.trim()).filter(Boolean); const { error } = await supabase.from('hunters').update({ status: byId('hunter-status-input').value.trim(), model: byId('hunter-model-input').value.trim(), load: byId('hunter-load-input').value.trim(), success_rate: Number(byId('hunter-success-rate-input').value || 0), avg_tokens: Number(byId('hunter-avg-tokens-input').value || 0), tags }).eq('id', hunter.id); if (error) { statusEl.textContent = `保存失败：${error.message}`; return; } statusEl.textContent = '保存成功'; await refresh(); }); renderHunterPage(hunter); }
async function initResourcePage() { const [{ data: kpis }, { data: models }] = await Promise.all([supabase.from('resource_kpis').select('*').order('sort_order'), supabase.from('resource_models').select('*').order('sort_order')]); byId('detail-title').textContent = '资源消耗总览'; byId('detail-subtitle').textContent = '按模型 / 任务 / 异常提醒继续追踪'; byId('detail-chip').textContent = 'TOKEN / COST'; byId('detail-summary').textContent = '这页承接首页的资源消耗模块，后续继续拆成任务消耗排行、猎人消耗排行、模型曲线。'; byId('detail-stats').innerHTML = renderPairs(kpis || []); byId('detail-side').innerHTML = renderPairs((models || []).map(item => ({ label: item.name, value: `${item.tokens || '-'} · ${item.cost || '-'}` }))); }
const mode = document.body.dataset.page; if (mode === 'task') initTaskPage().catch(console.error); if (mode === 'hunter') initHunterPage().catch(console.error); if (mode === 'resource') initResourcePage().catch(console.error);
